### ISSUE TITLE
nit: improve wording for log lines

### ISSUE THREAD

**Issue by greglockwood** [adRise/pr-auto-updater#5]
https://github.com/adRise/pr-auto-updater/blob/efeb4619d2849f3d824a1b4a1bc85a68d9469c2a/index.js#L17

Remove the word "branch" and consider adding a URL to make it easy to look at the PR.

https://github.com/adRise/pr-auto-updater/blob/efeb4619d2849f3d824a1b4a1bc85a68d9469c2a/index.js#L22

Suggestion:

```suggestion
log('🎉 Successfully updated.');
```

**Comment by zhiyelee** [comment]
@greglockwood Good catch, I planned to change the second one but forgot later. Feel free to create a PR.

**Comment by zhiyelee** [comment]
addressed wording in #7
